# Generated by Django 5.0.2 on 2024-02-15 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_serviceblock_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блока ')),
                ('description', models.TextField(verbose_name='Описание блока ')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блока сервисов')),
                ('description', models.TextField(verbose_name='Описание блока сервисов')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name2', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('position', models.PositiveSmallIntegerField(unique=True)),
                ('description', models.TextField(max_length=800, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, upload_to='about')),
                ('about_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='home.aboutblock', verbose_name='Блок сервисов')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('name2', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('position', models.PositiveSmallIntegerField(unique=True)),
                ('short_description', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=800, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('date', models.CharField(max_length=50, unique=True)),
                ('client', models.CharField(max_length=50, unique=True)),
                ('category_service', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='portfolio')),
                ('portfolio_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='home.portfolioblock', verbose_name='Блок сервисов')),
            ],
        ),
    ]
