# Generated by Django 5.0.2 on 2024-02-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutblock_portfolioblock_aboutunit_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutunit',
            old_name='name2',
            new_name='date',
        ),
    ]
