# Generated by Django 5.0.2 on 2024-02-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_shapka'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapka',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shapka',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
