# Generated by Django 5.0.2 on 2024-02-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_shapka_is_visible_shapka_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapka',
            name='position',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
    ]
