# Generated by Django 5.0.2 on 2024-02-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_brandname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=60, unique=True)),
                ('h2', models.CharField(max_length=60, unique=True)),
                ('button_name', models.CharField(max_length=60, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='face/')),
            ],
        ),
    ]
