# Generated by Django 5.0.2 on 2024-02-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_brandface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='name2',
        ),
    ]
