# Generated by Django 5.0.2 on 2024-02-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_portfolio_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category_service',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='client',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='short_description',
            field=models.CharField(max_length=255),
        ),
    ]
