# Generated by Django 5.0.2 on 2024-02-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_formcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блока ')),
                ('description', models.TextField(verbose_name='Описание блока ')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
