# Generated by Django 5.0.2 on 2024-02-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_contactblock_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brand', models.CharField(max_length=160)),
                ('terms_of_use', models.URLField(blank=True, max_length=255)),
                ('privacy_policy', models.URLField(blank=True, max_length=255)),
                ('instagram', models.URLField(blank=True, max_length=255)),
                ('facebook', models.URLField(blank=True, max_length=255)),
                ('linkedin', models.URLField(blank=True, max_length=255)),
            ],
        ),
    ]
